### PR TITLE
T29642 rebase on 1.8.x

### PR DESCRIPTION
**Pull request by mwleeds**
https://phabricator.endlessm.com/T29642

### CODE REVIEW

**Comment by mwleeds** [comment]
This rebase was pretty uneventful (only a couple merge conflicts docomented in the commit messages) so the review should focus mostly on whether any patches were inadvertently dropped and whether any upstream changes may cause problems.

**Comment by mwleeds** [comment]
The final commit "Fetch ostree-metadata for backwards compat" is brand new so deserves a bit more careful review than the rest.

**Comment by mwleeds** [comment]
Added three cherry-picks from upstream master that seem worth having

**Comment by pwithnall** [comment]
“eos: Allow metrics to be optional ” could be squashed into “eos: Add metrics submission on parental controls blocking run/install” (see its commit message).

I can’t see any problems otherwise

**Comment by mwleeds** [comment]
> “eos: Allow metrics to be optional ” could be squashed into “eos: Add metrics submission on parental controls blocking run/install” (see its commit message).

Did that and pulled six more commits from upstream master

**Pull request merged**
