### PR TITLE
T29642 rebase on 1.8.x (packaging)

### PR DESCRIPTION
**Pull request by mwleeds**
https://phabricator.endlessm.com/T29642

### CODE REVIEW

**Comment by mwleeds** [comment]
Excluding changelog entries, here's the diff between this branch and `debian-master`, with this branch as `flatpak2`:
```
diff -r debian/control ../flatpak2/debian/control
49a50
>  libzstd-dev,
53c54,55
<  python3 <!nocheck>,
---
>  python3:any,
>  python3-pyparsing,
diff -r debian/copyright ../flatpak2/debian/copyright
25c25
<  © 2018 Endless Mobile, Inc.
---
>  © 2018-2019 Endless Mobile, Inc.
diff -r debian/flatpak.install ../flatpak2/debian/flatpak.install
11a12
> usr/lib/sysusers.d
21a23
> usr/share/fish/vendor_completions.d
23c25
< usr/share/gdm/env.d
---
> usr/share/gdm/env.d/*                   usr/share/doc/flatpak/examples/etc/gdm3/env.d
Only in ../flatpak2/debian/: flatpak.README.Debian
diff -r debian/gbp.conf ../flatpak2/debian/gbp.conf
5c5
< upstream-branch = upstream/1.6.x
---
> upstream-branch = upstream/1.8.x
diff -r debian/libflatpak0.symbols ../flatpak2/debian/libflatpak0.symbols
16a17
>  flatpak_http_error_quark@Base 1.7.3
107d107
<  flatpak_oci_error_quark@Base 0.9.1
179a180
>  flatpak_transaction_add_sideload_repo@Base 1.7.0~git20200325
196a198
>  flatpak_transaction_operation_get_is_skipped@Base 1.7.3
200a203
>  flatpak_transaction_operation_get_related_to_ops@Base 1.7.3
221a225
>  flatpak_transaction_set_no_interaction@Base 1.7.3
Only in ../flatpak2/debian/: patches
diff -r debian/rules ../flatpak2/debian/rules
43a44
> 		--disable-auto-sideloading \
44a46
> 		--enable-gdm-env-file \
48a51
> 		--with-run-media-dir=/media \
```

**Comment by mwleeds** [comment]
Actually we do need another patch here, to pass `--with-run-media-dir=/run/media` to configure

**Comment by mwleeds** [comment]
I added a patch to pass `--enable-auto-sideloading` and `--with-run-media-dir=/run/media` to configure.

The only other change here compared to `debian-master` that looks important is there's `usr/lib/sysusers.d` in `flatpak.install` now, to let systemd create the `_flatpak` user for `flatpak-system-helper`. But [per the docs](https://www.freedesktop.org/software/systemd/man/sysusers.d.html#) systemd will only create a user defined in a sysusers.d file if it doesn't exist, so I think that should not conflict with our [existing base-passwd entry](https://github.com/endlessm/base-passwd/blob/master/passwd.master).

**Comment by mwleeds** [comment]
Pushed a fix for `debian/flatpak.install` so it contains the sideload units.

**Comment by pwithnall** [comment]
> ```
> diff -r debian/libflatpak0.symbols ../flatpak2/debian/libflatpak0.symbols
> 16a17
> >  flatpak_http_error_quark@Base 1.7.3
> 107d107
> <  flatpak_oci_error_quark@Base 0.9.1
> ```

Looks like neither of those symbols should ever have been exported. I’ve opened https://github.com/flatpak/flatpak/pull/3786 (which shouldn’t block this).

> The only other change here compared to `debian-master` that looks important is there's `usr/lib/sysusers.d` in `flatpak.install` now, to let systemd create the `_flatpak` user for `flatpak-system-helper`. But [per the docs](https://www.freedesktop.org/software/systemd/man/sysusers.d.html#) systemd will only create a user defined in a sysusers.d file if it doesn't exist, so I think that should not conflict with our [existing base-passwd entry](https://github.com/endlessm/base-passwd/blob/master/passwd.master).

Correct, `sysusers.d` entries are a no-op if the user is already listed in `base-passwd`, so it’s fine to leave them in the packaging.

**Pull request merged**
