### PR TITLE
Rebase on 1.1.3 (packaging)

### PR DESCRIPTION
**Pull request by mwleeds**
This is a rebase of our `debian-master` branch onto Debian's `debian/master` branch, with a `1.1.0` release commit added. There don't seem to have been many packaging changes since 1.0 since it's not very exciting.

### CODE REVIEW

**Comment by wjt** [comment]
retest this please! thanks bot

**Comment by wjt** [comment]
The PR build is failing for a legit reason:

 -> Considering build-dep libostree-dev (>= 2018.7)
      Tried versions: 2018.6+dev95.46c55c1-13bem1
   -> Does not satisfy version, not trying
E: Could not satisfy build-dependency.

**Comment by mwleeds** [comment]
Ah yeah we have every commit in 2018.7 but not the one that changes the version number

**Comment by mwleeds** [comment]
This branch is now rebased on Debian's packaging branch for 1.1.3, but we won't be able to see if Jenkins can build it until the OSTree rebase is merged.

**Pull request merged**
