### PR TITLE
installation: Return main app as updatable if related extensions are missing

### PR DESCRIPTION
**Pull request by uajain**
(Subset) Backport of https://github.com/flatpak/flatpak/pull/3204

https://phabricator.endlessm.com/T28302

### CODE REVIEW

**Comment by pwithnall** [comment]
(Pending [updates upstream](https://github.com/flatpak/flatpak/pull/3204#pullrequestreview-314970610))

**Comment by uajain** [comment]
Resynced with what's [upstream](https://github.com/flatpak/flatpak/pull/3204)

**Comment by uajain** [comment]
> Resynced with what's [upstream](https://github.com/flatpak/flatpak/pull/3204)

Merged upstream.

**Comment by uajain** [comment]
@wjt Are you planning to review this downstream backport or should I land this?

**Pull request merged**
