### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by andrunko**
Fixes for some small issues found while testing.

### CODE REVIEW

**Comment by uajain** [comment]
Upstream PR is here: https://github.com/flatpak/flatpak/pull/3025/

@andrunko Generally we wait for the upstream PR to get merged and backport those patches by opening a new PR downstream. The backported patches in the downstream PR have a mention of which patches are being backported (mention their commit_id)from upstream, in their commit message. This way:
1. Reviews are not split across 2 PRs (upstream and downstream)
2. Rebases gets easier (just drop  the backported patches when rebasing the newest version)

**Comment by andrunko** [comment]
> Upstream PR is here: [flatpak/flatpak#3025](https://github.com/flatpak/flatpak/pull/3025)
> 
> @andrunko Generally we wait for the upstream PR to get merged and backport those patches by opening a new PR downstream. The backported patches in the downstream PR have a mention of which patches are being backported (mention their commit_id)from upstream, in their commit message. This way:
> 
> 1. Reviews are not split across 2 PRs (upstream and downstream)
> 2. Rebases gets easier (just drop  the backported patches when rebasing the newest version)

While I agree with your rationale, I don't think we should wait for upstream before integrating the changes downstream specially if the changes are actual fixes, which is the case for one of the fixes here.   For the leaks I agree they can wait.

**Comment by andrunko** [comment]
Anyway, the upstream changes landed already (faster than I though) so I will update the changes here to cherry-pick the changes from upstream and update the commit msgs with the upstream commit.

**Comment by andrunko** [comment]
Updated changes to cherry pick commits from upstream (and mentioned the upstream commits in the commit msgs).

**Pull request merged**
