### PR TITLE
Reapply downstream translations

### PR DESCRIPTION
**Pull request by wjt**
https://phabricator.endlessm.com/T28002

### CODE REVIEW

**Comment by wjt** [comment]
Weird. I haven't changed anything which should cause test failures, but indeed when I run the tests locally they fail (though a different set) and then toolbox crashes.

**Comment by wjt** [comment]
retest this please

**Comment by wjt** [comment]
```
flatpak:ERROR:../../tests/testcommon.c:305:test_number_prompt: assertion failed (g_print_buffer->str == "Prompt 1 ? [0-8]: 0\n"): ("Prompt 1 ? [0-8]: 0\n# GLib-DEBUG: posix_spawn avoided (fd close requested) \n" == "Prompt 1 ? [0-8]: 0\n")
```

**Comment by wjt** [comment]
What's happening is that the test is meant to be capturing the human-facing output stream, and:

```
# GLib-DEBUG: posix_spawn avoided (fd close requested) \n
```

is getting mixed in there. I have run the test in a loop locally and cannot reproduce so I'm giving up for today.

**Comment by pwithnall** [comment]
```
`flatpak:ERROR:../../tests/testcommon.c:305:test_number_prompt: assertion failed (g_print_buffer->str == "Prompt 1 ? [0-8]: 0\n"): ("Prompt 1 ? [0-8]: 0\n# GLib-DEBUG: posix_spawn avoided (fd close requested) \n" == "Prompt 1 ? [0-8]: 0\n")`
```

Interesting. Presumably a background thread is sometimes spawning a subprocess at the same time as this test is checking the `stdout` output. Maybe these tests should be run with `G_MESSAGES_DEBUG=` (unset)? In any case, something for a follow-up issue.

**Comment by wjt** [comment]
https://github.com/flatpak/flatpak/issues/3207

**Pull request merged**
