### PR TITLE
Backports from 1.8.4 and 1.8.5

### PR DESCRIPTION
**Pull request by mwleeds**
https://phabricator.endlessm.com/T31239

### CODE REVIEW

**Review by andrunko — CHANGES_REQUESTED** [review]
Changes LGTM except that one of the tests is failing, please check.

**Comment by mwleeds** [comment]
Yeah looks like it's trying to load `libasan.so.4` and not finding it. Probably needs packaging changes, I'll check.

**Comment by mwleeds** [comment]
bot, retest this please

**Comment by mwleeds** [comment]
Oh, looks like CI is also failing upstream on the flatpak-1.8.x branch, so this issue isn't downstream.

**Comment by andrunko** [comment]
Should we disable the test then?

**Review by andrunko — APPROVED** [review]

**Comment by mwleeds** [comment]
Pulled one commit from upstream master. Looks good to merge now.

**Pull request merged**
